sudo: false
dist: trusty

language: node_js
node_js:
  - "8" # LTS

notifications:
  email:
    on_success: never
    on_failure: change

script:
  # automatic labels setting.
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]] ; then
      npm install @azu/github-label-setup -g
      github-label-setup --token $GITHUB_TOKEN --labels $TRAVIS_BUILD_DIR/labels.json
    fi